[package]
name = "dag_faas"
version = "0.1.0"
edition = "2024"

[dependencies]
arrow = "55.0.0"
arrow-flight = "55.0.0"
tonic = "0.12.3"
tokio = {version = "1", features = ["full"]}
petgraph = "0.6.0"
prost = "0.13"
futures = "0.3"
anyhow = "1.0"

[build-dependencies]
tonic-build = "0.12.3"
